### ISSUE TITLE
[Anon] Bug report: Bagration_Germany.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/flamesofwar#20]
**File:** Bagration_Germany.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Bagration, recon company missing all the sdkfz 250 on reconaissane platoon and the option to put 7 mg42 teams too at the max cost of 16 points each platoon.
Hq missing the 250 carriers too

**Comment by hav3rchuck** [comment]
They are there, but they are a little hidden.

Click on '2x MP40 SMG Team' to drill in for the option for the HQ and for the platoons to drill into the '5x MG42' and '7x MG42' to see the option.
