### ISSUE TITLE
[Anon] Bug report: Bagration_Germany.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/flamesofwar#21]
**File:** Bagration_Germany.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Bagration support platoon
10,5 and wespe or 10,5 and hummel not showing all the options. Missing the 4 10,5 or the armoured versions.
Panzerwerfer and nebelwerfer only shows 1 option, missing the 3 or 6 nebelwerfer or the 2 or 4 panzerwerfer

**Comment by hav3rchuck** [comment]
These both exist, but you need to click on the option itself (not the radial button) and drill into see the options.  They exist, but it is not shown without clicking on the titles.
