### ISSUE TITLE
Armoured Fist?

### ISSUE THREAD

**Issue by nottsknight** [BSData/flamesofwar#24]
Just wondering if there are plans to add the Armoured Fist book? As the other three North Africa books are already here :)

**Comment by hav3rchuck** [comment]
Just need to get the book to be able to put them in ;-)

**Comment by AnhNhan** [comment]
I have the book. Would anyone mind me trying myself at this, or should I send pics your way?

**Comment by Tilioch** [comment]
Sure you can have a go at it, the more that contributes the better!

**Comment by AnhNhan** [comment]
I added a basic draft without command cards. I did stumble upon an issue though, see the PR.

**Comment by hav3rchuck** [comment]
Will look at it this week.  Was AFK for a few weeks. :-)

**Comment by hav3rchuck** [comment]
Closing duplicate issues (see #25 )
