### ISSUE TITLE
American and German Bulge

### ISSUE THREAD

**Issue by BranSUFC** [BSData/flamesofwar#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BranSUFC** [comment]
Just curious as to why bulge American and German isn’t on BattleScribe?

**Comment by Willus8888** [comment]
I do American Bulge and have done bit of German based on what has been released online (so a WIP).

**Comment by WolfHunter88** [comment]
I know this is your hobby and not a job let alone full time but what is a good eta for the bulge expansions?

**Comment by Willus8888** [comment]
Ive become extremely unwell atm. US Bulge units done just need to organise into formations. havent started German. See projects.
Happy to offload if someone is wanting to give it a crack.

**Comment by BranSUFC** [comment]
Also I have both bulge books so if you need anything, let me know :)

**Comment by WolfHunter88** [comment]
Sorry to hear that and I hope you get well soon!!  I am not much at programming but I am willing to help to the best of my abilities.  What kind of things would help you after your recovery (focus on your health and wellness first, this is just a game)?

**Comment by Edivad42** [comment]
> Ive become extremely unwell atm. US Bulge units done just need to organise into formations. havent started German. See projects. Happy to offload if someone is wanting to give it a crack.

I MIGHT be able to start doing bulge german in the future, if so I'll mark it on projects. It probably won't be very soon though.

**Comment by Willus8888** [comment]
As i slowly get better i can start back on US. I wont be able to do German though. If someone else could do this than that would be awesome!

**Comment by Edivad42** [comment]
@Willus8888 It seems I'm not able to edit the Bulge German project, not super expert of github, do you need to assign it to me?

**Comment by Willus8888** [comment]
> @Willus8888 It seems I'm not able to edit the Bulge German project, not super expert of github, do you need to assign it to me?

Im not sure either. Ive deleted the German Bulge project.

**Comment by Willus8888** [comment]
I'll start back up on US Bulge tomorrow.

**Comment by WolfHunter88** [comment]
I ordered the German Bulge book and unit cards; when it arrives what can I do to help complete the German Bulge project?  I don't know programming but I can provide data, make spreadsheet, etc.

**Comment by Willus8888** [comment]
> I ordered the German Bulge book and unit cards; when it arrives what can I do to help complete the German Bulge project? I don't know programming but I can provide data, make spreadsheet, etc.

PM me

**Comment by Edivad42** [comment]
Thank you @WolfHunter88, unfortunately I already have all the info needed, I already begun adding some unit statline, but in the last weeks I haven't had time to proceed, and I don't think it will be a fast process.
Good news is that no advanced programming skill is needed to contribute, it's just a bit hard to find info on how to do it, so if you have some free time could be worth it to try and do it yourself.

**Comment by Willus8888** [comment]
maybe collab together on the same data file?

**Comment by Willus8888** [comment]
I've got a few fixes to do on the American Bulge as well as add the 2nd half of cmd cards.
I've been playing around a lot with conditions irt command cards and how it affects units and their stats.

**Comment by WolfHunter88** [comment]
I am totally down to help.  Where can I go to start learning some programming to help?

**Comment by Willus8888** [comment]
> I am totally down to help.  Where can I go to start learning some programming to help?

Might be best to liase with @Edivad42 .
He could start his own repo for that single file and you to work together on it, commiting changes etc. Then once you both think your done then do a pull request to here.

Just a thought.
