### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Edivad42** [BSData/flamesofwar#34]
### Your Discord

Edivad

### Additional information

Hi,
I'm in the process of adding Command Cards to D-Day British (and maybe contribute more in the future), I would like to join, thanks.

**Comment by Mad-Spy** [comment]
@Willus8888 @hav3rchuck @obsidian20-uk 

You three have most recently commented or contributed to this repo. Please can you respond to this join request?

**Comment by hav3rchuck** [comment]
Hi Mad-Spy.

Please fork the repo and make a pull request.  Then we merge your branch into master once checked.

**Comment by Edivad42** [comment]
It's actually me asking to join, I guess I'll make the fork and pull request.

**Comment by hav3rchuck** [comment]
Did you fork the repo?

**Comment by hav3rchuck** [comment]
From your repo, you initiate the pull request.

**Comment by Edivad42** [comment]
Ok, I won't be at the PC where I have the updated files until next week, but thanks for the info.
