### ISSUE TITLE
[Anon] Bug report: Flames of War.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/flamesofwar#4]
**File:** Flames of War.gstz

**BattleScribe version:** 2.01.16

**Platform:** Android

**Dropbox:** No

**Description:** no roster will load, it lists errors like " all items must be unique" and when It loads there's just a blank page.

**Comment by Tilioch** [comment]
This issue is related to the v3 files, these will be phased outand any error in them will not be fixed by current crew
