### ISSUE TITLE
their are two D-Day British.cat in the repo

### ISSUE THREAD

**Issue by Willus8888** [BSData/flamesofwar#40]
**Describe the bug**
Two D-Day British.cat
One named D-Day_British.cat, the other D-Day British.cat

**Expected behavior**
Merge into one

**Screenshots**
<img width="910" alt="Screen Shot 2022-08-22 at 16 34 30" src="https://user-images.githubusercontent.com/29905193/185840339-092f4df9-6188-4c5c-bb03-76f6d4956a2e.png">

**Comment by mdcooledge** [comment]
Deleted D-Day_British.cat (v5) and renamed D-Day British.cat (v6) to D-Day_British.cat (v6).
