### ISSUE TITLE
Mid war Soviets, Enemy at the gates and Red banner?

### ISSUE THREAD

**Issue by BranSUFC** [BSData/flamesofwar#53]
Hi guys, would anyone kindly be able to open a project for mid war soviets for BS? We have mid war Germans already. 
axis Allies would also be great but I understand that they aren’t as popular so is a long shot.

thanks in advance guys!

**Comment by mdcooledge** [comment]
@BranSUFC Who has the ability to open projects? I could use one to help me finish up the Bulge: German, and start up Berlin: Germans.

**Comment by BranSUFC** [comment]
No idea mate I was just asking the question lol

I’d help myself if I had some idea with code, I would have imagined with Berlin German only just being released, Berlin Soviets might be more of a priority

**Comment by mdcooledge** [comment]
@BranSUFC I got ya. I've been working on the German Books as that is what I own. If I had the other books I would happily work on those as well.

**Comment by AncestralHeritage** [comment]
I've just started learning to use GitHub because I noticed that these 2 soviet books are not available. I don't know how to code much either but fingers crossed, I might eventually manage to help you guys.

**Comment by mdcooledge** [comment]
@AncestralHeritage Go for it! We need all the help we can get. We also need the Berlin: Soviet book added as well. I just don't have that book or I would do it myself. Check out any of the data files to reference, Bulge and Berlin: German's are the latest. Let me know if you have questions, I will be happy to help the best I can. Join the BSData discord and you can find me there with the same username. Best of luck!

**Comment by BranSUFC** [comment]
> @BranSUFC I finally got access to help with this repo. What book(s) are the mid war soviets in? I will create a project so that it can be worked on when possible.

Hi bud. 

Sorry for late response, the mid war soviets are in that new mid war compilation book, but their individual books are called ‘enemy at the gates’ and ‘Red Banner’

**Comment by AncestralHeritage** [comment]
Since those books are included in the Fortress Europe book, maybe we could create 2 different files separate for each book. I'm working on Berlin now so this is not a priority

**Comment by AncestralHeritage** [comment]
You can close this thread. I just did a merge request for Mid-War soviets from the new Eastern Front Mid-War Forces book. Both EatG and RB are included + some few extra formations and wildcards.
