### ISSUE TITLE
American  bulge  battle weary armor rife company 

### ISSUE THREAD

**Issue by CircuitJack** [BSData/flamesofwar#56]
When selecting a battle weary armor rifle company  the option to change the size of the unit  from 4rifleman to 6 is bugged 
sometimes you have to delete the unite 
to select the right size 

next problem
 Is the sub menu that shows
  2 m4 haft tracks  with 50 cal and 2 with  a 30 cal 
If the larger unit is selected the option  above  should change to this 
2 m4 haft tracks  with 50 cal and 3 with  a 30 cal 
@ 3 points

**Comment by mdcooledge** [comment]
@CircuitJack Hey, just following up on this bug report. This is the Bulge: Americans? Also, what platform are you experiencing this on, PC, Android, or iOS? I can't seem to replicate the bugged 4 to 6 man change on both PC or iOS.

**Comment by CircuitJack** [comment]
It's a bug on android using a galaxy s22 ultra ok looks like  it's just  the haft tracks  are not correct  I was just being  dumb  but if you take the 

6x m1 garand rifle teams and 5x bazooka  teams

They can only add the attachment of 
2x 50cal haft tracks  and 3x 30cal haft tracks for 3points 

^this option  is missing 

The only option is the
2x 50cal haft tracks and 2x 30cal haft tracks for 2points

And only a 
4x m1 garand rifle teams and 4 bazooka  option can take that

**Comment by CircuitJack** [comment]
![Screenshot_20230509_095311](https://github.com/BSData/flamesofwar/assets/87613674/9c6a0e3a-4d32-4820-94c3-0f19be0b0da7)
Here's a screen shot there should be 2 option  or only 1 that has  the correct  amount of haft tracks  for the selected  unit size  

Sorry hit the close button by mistake

**Comment by CircuitJack** [comment]
![Screenshot_20230509_100857_Chrome](https://github.com/BSData/flamesofwar/assets/87613674/60c60816-92ed-4108-9b16-cb7f9bb95610)

**Comment by mdcooledge** [comment]
@CircuitJack Awesome. Thanks for clarifying and adding the screenshots. It really helps as I really only have the Books for the German forces. I will update this as soon as I can and let you know. Currently working through Berlin: Germans. Also, keep on the look out for any other issues, just post them under bugs. Thanks!
