### ISSUE TITLE
Bug report: D-Day_German.catz

### ISSUE THREAD

**Issue by Hypnoshizu** [BSData/flamesofwar#59]
File: D-Day_German.catz

BattleScribe version: 2.03.21

Platform: PC

Dropbox: No

Description: The D-Day Germans are missing their Artillery Observer in form of the Panzer III OP 

![Screenshot 2023-05-24 210419](https://github.com/BSData/flamesofwar/assets/107074800/56fe44f4-c150-4918-b172-6e11636e5eb7)

**Comment by Hypnoshizu** [comment]
I checked again and I can not find any Observers other than in Berlin Germans and Bulge German

**Comment by mdcooledge** [comment]
@Hypnoshizu Thanks for bringing this up. I will take a look and see what I can find. I will probably go through both german d day books and bring them more inline with the Berlin and Bulge layouts. Keep you posted.

**Comment by mdcooledge** [comment]
@Hypnoshizu I figured it out. It stays hidden until you choose one of the artillery units that the Panzer III OP requires first. Then if you go back to the support units, then it will be displayed.

**Comment by Hypnoshizu** [comment]
@mdcooledge just checked and you are right. Thanks for clearing things up.

Best Regards,
Charlie

**Comment by mdcooledge** [comment]
@Hypnoshizu Question for you regarding this. Do you think it's more user friendly to have the OP unit remain hidden until the required artillery units are selected, like it is currently? OR would it be more user friendly to have the OP unit visible but if it is selected AND the required artillery units are NOT selected it throws an error message that says you must have the required artillery units selected? What do you think would be best for yourself and others?

**Comment by mdcooledge** [comment]
No issues.
