### ISSUE TITLE
[Anon] Bug report: Fortress_Europa_German.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/flamesofwar#6]
**File:** Fortress_Europa_German.catz

**BattleScribe version:** 2.03.03

**Platform:** Android

**Dropbox:** No

**Description:** Panzergrenadier platoon seems to be missing the panzershrek team option (the two man bazooka squad) it has the panzerfaust upgrade option but not the additional team option.

**Comment by Tilioch** [comment]
This is not an option for the Panzergrenadier platoon in Fortress Europe, this is from D-day: German so this will be in the forthcoming catalog for that german book
