### ISSUE TITLE
[Anon] Bug report: D-Day_British.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/flamesofwar#61]
**File:** D-Day_British.catz

**BattleScribe version:** 2.03.27

**Platform:** Android

**Dropbox:** No

**Description:** Observation Post unit disappear from the support units opciones.

**Comment by mdcooledge** [comment]
Hey there, as it is configured currently, the OP unit in formation support only shows when one of the precursor artillery units is added to the formation. It is hidden when there is none of the artillery units in the formation. Let me know if there a specific unit that this is broken for so I can take a look. Thanks!
