### ISSUE TITLE
Berlin german

### ISSUE THREAD

**Issue by LordPapkin** [BSData/flamesofwar#64]
Hi, there is mistake in jagdtiger support, there should be 1/2/3 not 2/3/4
![image](https://github.com/BSData/flamesofwar/assets/79983335/88c78115-17db-4b02-b117-ca38f3c00265)

**Comment by mdcooledge** [comment]
Hey @LordPapkin,

Thanks for pointing this out. The corrections have been made and will be available upon the next release. As always if you find any other errors please let us know.

Morgan
