### ISSUE TITLE
Asking for access

### ISSUE THREAD

**Issue by LordPapkin** [BSData/flamesofwar#69]
### Your Discord

lordpapkin

### Additional information

Hi, i got multiple German, Axis allies and Soviet books and command cards, i would like to help expand some parts of repo. I didnt work with battlescribe before but i got software background so i think i will handle that.

**Comment by mdcooledge** [comment]
@LordPapkin Were you able to get the access you needed?

**Comment by LordPapkin** [comment]
@mdcooledge yea, i think i have everything i need but i just got too busy to add something

**Comment by LordPapkin** [comment]
i think i will start with adding command card for fins (late-war)

**Comment by mdcooledge** [comment]
No worries. Do what you can when you can. If you have any questions just let me know and I will help the best I can. I am going to close out this issue.
