### ISSUE TITLE
[Join Request] to contribute to FoW

### ISSUE THREAD

**Issue by TeaStar** [BSData/flamesofwar#7]
Hi, I would like to contribute by adding the Armoured Fist book. As a developer, I already have plenty of git experience and the data editor looks straight forward to use. I will use an existing file for reference. 

Thanks,
Dan.

**Comment by amis92** [comment]
@Tilioch ? You can invite @TeaStar if you'd like to at: https://github.com/BSData/flamesofwar/settings/collaboration

**Comment by Tilioch** [comment]
Hello, @TeaStar.
Did not know I could invite, but now you should be able to accept the invitation by email or this [link](https://github.com/BSData/flamesofwar/invitations)
Let me know if there is anything I can help with, other than that, do nuts and add any book you have access to!

**Comment by TeaStar** [comment]
Great. Thanks.
