### ISSUE TITLE
Streamlining of Formatting

### ISSUE THREAD

**Issue by UrsinePatriarch** [BSData/flamesofwar#70]
Hello!
I've worked on more than my fair share of Battlescribe files over the years (Age of Sigmar, Dystopian Wars, Battlefleet Gothic, Horus Heresy) and would like to suggest formatting changes to how the Flames of War files are handled.

If I re-format Afrika Korps in a style that I feel is more user and editor friendly (more in-line with how other data files are handled, proper placement of Selection Entries, usage of Selection Entry Groups, etc), would this be something you'd be interested in allowing me to do myself/teach someone else how to do for the rest of the files?

As it stands, the current layout is almost unusable on phone and somewhat bothersome to use on PC; entries in entries in entries, too much text preventing users from reading the options, unclear options from the start of a menu, etc etc, I could go on. I'd like to help remove these annoyances for both my own usage and that of others going forward.

**Comment by mdcooledge** [comment]
Go for it! I didn't create any of the initial data/formating, I only added some of the later book copying the format of what was started. If you can clean it up and make it more usable, then I am all for it. I don't think the data is updated much anymore but I am not going to stop you. Thanks for your help!

**Comment by UrsinePatriarch** [comment]
Perfect!
I'll start work immediately and should have something approaching workable formatting next week; I'll post it here for you to review and if it looks good, I'll probably slowly work my way through the files over time.

Any idea who the original editor is? Doesn't seem like he's in the Discord so I figured I might find him here.

**Comment by mdcooledge** [comment]
Awesome. I'm excited to see what you come up with. I have no clue who the original editor was. I tried reaching out to several people a few years ago when I got started with no luck. I think I was given editor permissions by the BSData guy after I let them know I couldn't get access. I did most of the German stuff as that's the only books I have. Some of the Soviets and stuff as well. I think I am currently the only "active" contributor to this data but welcome your help!

**Comment by hav3rchuck** [comment]
I have also edited quite a few of the files and just followed in the of the original. That said, a complete overhaul of all of it would be great.  Especially things like having global rules being in the main over-arching FoW army file, etc.

I am curious to see what you have in mind.  I think if a few of us work together, we could get a nice way to make it a good experience of the user and also for the maintainers of the files themselves.

**Comment by hav3rchuck** [comment]
Sounds great!  I look forward to see what you come up with for organizing to make mobile usage nicer!

**Comment by UrsinePatriarch** [comment]
Well, I finished up Afrika Korps (for the most part), but now I'm discovering they added more units in the recent North Africa book, so I guess I'll be doing my best to add those with what information I can skim offline.

Also, Fallschirmjager can be added to any Mid-War German force, so I'm looking at making them a Library that can be added to DAK, Ghost Panzers, and Iron Cross (even if I'm not sure who's legal anymore cause V4 is confusing as hell).

**Comment by mdcooledge** [comment]
Awesome! Yeah I have no mid-war books and since they combined all of them into two (North Africa and Eastern Front), I don't know if that would make combining all the data easier to manipulate combined or not. I know they are in the process of doing the same with all the Late War Books as well.

**Comment by UrsinePatriarch** [comment]
Generally, it's a bad idea to combine catalogs; even if it makes a smoother interface, it causes a bloated catalog full of unrelated bits. For instance, I could make a "Mid-War: Germany" catalog that combines 3 separate catalogs (DAK, Ghost Panzers, Iron Cross) and have something like 6 different Panzer IIIs alone with all of them needing to be kept separate for their specific purposes.

I would, however, suggest adding "Mid-War" and "Late-War" as suffixes for the catalogs to better stratify them visually.

**Comment by UrsinePatriarch** [comment]
@mdcooledge @hav3rchuck 
I have uploaded my work and wish for your review/approval; do take your time as it's now the weekend, I imagine.
Thanks for your time o7
