### ISSUE TITLE
[Anon] Bug report: D-Day_German.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/flamesofwar#8]
**File:** D-Day_German.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** Panzer schreck points under panzergrenadier  for two of the choices states 1 point instead of 2 points

**Comment by Tilioch** [comment]
I'll have a look at this as soon as I can in the new year.

**Comment by Tilioch** [comment]
Issue fixed in release 1.1.8
