### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Ruharc85** [BSData/flamesofwar#9]
Hey,

I would like to contribute to the project. 
I could offer to write the catalogue for "Enemy at the gates" and "Red Banner". I also have the British books.

Cheers
Paul

**Comment by Tilioch** [comment]
Hello!
Welcome and it would be great with some more help. You have an invite on your mail or in this link https://github.com/BSData/flamesofwar/invitations

Please add any book you have access to.
